AtchooClient/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Web;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace AtchooClient.Models
{
  public class UserProfile
  {
    public UserProfile()
    {
      this.JoinEntities = new HashSet<ProfileAllergy>();
    }
    
    public int UserProfileId { get; set; }
    [Required]
    public string Name { get; set; }
    [Required]
    public string DOB { get; set; }
    [Required]
    public string Bio { get; set; }
     [NotMapped]
    public IFormFile FrontImage { get; set;}
    public string ImageUrl { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<ProfileAllergy> JoinEntities { get; }
  }
}

AtchooClient/Controllers/UserAllergiesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using AtchooClient.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AtchooClient.Controllers
{
  [Authorize]
  public class UserAllergiesController : Controller
  {
    private readonly AtchooClientContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public UserAllergiesController(UserManager<ApplicationUser> userManager, AtchooClientContext db)
    {
      _userManager = userManager;
      _db = db;
    }
   
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<UserAllergy> model = _db.UserAllergies.ToList();
      // ViewBag.UserProfiles = _db.UserProfiles.ToList();
      ViewBag.ProfileAllergies = _db.ProfileAllergies.ToList();
      return View(model);
    } 
    public ActionResult Details(int id)
    {
      var thisAllergy = _db.UserAllergies
        .Include(userAllergy => userAllergy.JoinEntities)
        .ThenInclude(join => join.userProfile)
        .FirstOrDefault(userAllergy => userAllergy.UserAllergyId == id);
      return View(thisAllergy);
    }

    public ActionResult Create()
    {
      ViewBag.UserAllergyId = new SelectList(_db.UserAllergies, "UserAllergyId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(UserAllergy userAllergy)
    {
      bool exists = _db.UserAllergies.Any(a => a.Allergy.ToUpper() == userAllergy.Allergy.ToUpper());
      if(!exists)
      {
        _db.UserAllergies.Add(userAllergy);
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisAllergy = _db.UserAllergies.FirstOrDefault(userAllergy => userAllergy.UserAllergyId == id);
      return View(thisAllergy);
    }

    [HttpPost]
    public ActionResult Edit(UserAllergy userAllergy)
    {
      _db.Entry(userAllergy).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisAllergy = _db.UserAllergies.FirstOrDefault(userAllergy => userAllergy.UserAllergyId == id);
      return View(thisAllergy);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisAllergy = _db.UserAllergies.FirstOrDefault(userAllergy => userAllergy.UserAllergyId == id);
      _db.UserAllergies.Remove(thisAllergy);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

  }
}

AtchooClient/Controllers/UserProfilesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using AtchooClient.Models;
using System.IO;
using System.Web;
using Microsoft.AspNetCore.Hosting;
using AtchooClient.ViewModels;
using System;


namespace AtchooClient.Controllers
{
  [Authorize]
  public class UserProfilesController : Controller
  {
    private readonly AtchooClientContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IWebHostEnvironment webHostEnvironment;

    public UserProfilesController(UserManager<ApplicationUser> userManager, AtchooClientContext db,IWebHostEnvironment webHost)
    {
      _userManager = userManager;
      _db = db;
      webHostEnvironment =webHost;
    } 
  
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userProfile = _db.UserProfiles.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(userProfile);
    }
    public ActionResult Create()
    {
      ViewBag.UserAllergyId = new SelectList(_db.UserAllergies, "UserAllergyId", "Allergy");
      return View();
    }
     public string UploadFile(UserProfile userProfile)
    {
      string uniqueFilName = null;
      if(userProfile.FrontImage!=null)
      {
        string uploadFolder =Path.Combine(webHostEnvironment.WebRootPath,"img");
        uniqueFilName = Guid.NewGuid().ToString()+"_"+ userProfile.FrontImage.FileName;
        string filePath =Path.Combine(uploadFolder,uniqueFilName);
        using(var fileStream = new FileStream(filePath,FileMode.Create))
        {
          userProfile.FrontImage.CopyTo(fileStream);
        }
      }
      return uniqueFilName;
    }

    [HttpPost]
    public async Task<ActionResult> Create(UserProfile userProfile, int UserAllergyId)
    {
      // string fileName =Path.GetFileNameWithoutExtension(userProfile.ImageFile.FileName);
      // string extension =Path.GetExtension(userProfile.ImageFile.FileName);
      // fileName = fileName + extension;
      // userProfile.ProfileImg ="~/wwwroot/img/" + fileName;
      // fileName =Path.Combine(Server.MapPath("~/wwwroot/img/"),fileName);
      // userProfile.ImageFile.SaveAs(fileName);
     
      
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      userProfile.User = currentUser;
       string uniqueFilName =UploadFile(userProfile);
      userProfile.ImageUrl =uniqueFilName;
      _db.Attach(userProfile);
      

      _db.UserProfiles.Add(userProfile);
      _db.SaveChanges();
      if (UserAllergyId != 0)
      {
        _db.ProfileAllergies.Add(new ProfileAllergy() { UserAllergyId = UserAllergyId, UserProfileId = userProfile.UserProfileId });
      }
      _db.SaveChanges();
      ModelState.Clear();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      ViewBag.UserAllergies = _db.UserAllergies.ToList();
      var thisUserProfile = _db.UserProfiles
        .Include(userProfile => userProfile.JoinEntities)
        .ThenInclude(join => join.userAllergy)
        .FirstOrDefault(userProfile => userProfile.UserProfileId == id);
      return View(thisUserProfile);
    }
    public ActionResult Edit(int id)
    {
      var thisUserProfile = _db.UserProfiles.FirstOrDefault(userprofile => userprofile.UserProfileId == id);
      ViewBag.UserAllergyId = new SelectList(_db.UserAllergies, "UserAllergyId", "Allergy");
      return View(thisUserProfile);
    }
    [HttpPost]
    public ActionResult Edit(UserProfile userprofile)
    {
      string uniqueFilName =UploadFile(userprofile);
      userprofile.ImageUrl =uniqueFilName;
      //  _db.Attach(userprofile);
      // _db.Attach(userprofile);
      _db.Entry(userprofile).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddAllergy(int id)
    {
      var thisUserProfile = _db.UserProfiles.FirstOrDefault(userProfile => userProfile.UserProfileId == id);
      ViewBag.UserAllergyId = new SelectList(_db.UserAllergies, "UserAllergyId", "Allergy");
      return View(thisUserProfile);
    }
    [HttpPost]
    public ActionResult AddAllergy(UserProfile userprofile, int UserAllergyId)
    {
      bool exists = _db.ProfileAllergies.Where(p => p.UserProfileId == userprofile.UserProfileId).Any(a => a.UserAllergyId == UserAllergyId);
      if(UserAllergyId != 0 && !exists)
      {
        _db.ProfileAllergies.Add(new ProfileAllergy() {UserAllergyId = UserAllergyId, UserProfileId = userprofile.UserProfileId});
        _db.SaveChanges();
      }
      else
      {
        return RedirectToAction("ThankYou");
      }
      return RedirectToAction("Details", new {id = userprofile.UserProfileId});
    }
    public ActionResult ThankYou()
    {
      TempData["alertMessage"] = "<script>alert('You've Already added this Allergy');</script>";
      return View();
    }
    [HttpPost]
    public ActionResult DeleteAllergy(int joinId)
    {
      var joinEntry = _db.ProfileAllergies.FirstOrDefault(entry => entry.ProfileAllergyId == joinId);
      _db.ProfileAllergies.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisUserProfile = _db.UserProfiles.FirstOrDefault(userprofile => userprofile.UserProfileId == id);
      return View(thisUserProfile);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisUserProfile = _db.UserProfiles.FirstOrDefault(userprofile => userprofile.UserProfileId == id);
      _db.UserProfiles.Remove(thisUserProfile);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

AtchooClient/Views/UserProfiles/AddAllergy.cshtml
@model AtchooClient.Models.UserProfile


<h4>Add an Allergy to your profile @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.UserProfileId)

  @Html.Label("Select Allergy")
  @Html.DropDownList("UserAllergyId")

  <input type="submit" value="Save" class="btn btn-primary"/>
}

AtchooClient/Views/UserProfiles/Create.cshtml
@model AtchooClient.Models.UserProfile

<h4>Create Your Profile</h4>

<div class= "inner-content"
    style="
    display: flex;
    justify-content: center;
    margin-left: 30%">

      <div class="form-wrap" style="margin: 0 auto;">

            @using (Html.BeginForm("Create","UserProfiles",FormMethod.Post,new {enctype ="multipart/form-data"}))
            {
              <div class = "form" style="width: 200%;">

                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { required = "required" })

                @Html.Label("Date of Birth")
                @Html.TextBoxFor(model => model.DOB, new { required = "required", @type = "date", value = "model.DOB" })

                @Html.LabelFor(model => model.Bio)
                @Html.TextAreaFor(model => model.Bio, new { required = "required", maxlength=250, @class = "form-control" })
                
                <input  type="file" name="FrontImage" />

                @Html.Label("Select Allergy")
                @Html.DropDownList("UserAllergyId")

                <input class="button" type="submit" value="create profile" class="btn btn-primary" />

              </div>
            }

      </div>

</div>

AtchooClient/Views/UserProfiles/Delete.cshtml
@model AtchooClient.Models.UserProfile

<h2>Do you want to delete this User from database?</h2>

<h4>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  <input class = "myCssClass" type="submit" value="Delete" />
}
<br>
@Html.ActionLink("Back to your profile", "Index")

AtchooClient/Views/UserProfiles/Details.cshtml
@model AtchooClient.Models.UserProfile

<div class="user-page">

    <div class="user-card-title">
        <h2 style='color: white; transform: scale(1.3);'>User Details</h2>
    </div>


  <div class="user-card">

    <div class="user-card-content">

        <div class="user-card-content-deets">

          <div class="user-card-info"
            style="
              display: grid;
              grid-template-rows: 1fr 1fr;
              justify-content: left;
          ">
              <h4>@Html.DisplayNameFor(model => model.Name):</h4> <p>@Html.DisplayFor(model => model.Name)</p>
              <h4>@Html.DisplayNameFor(model => model.DOB):</h4> <p>@Html.DisplayFor(model => model.DOB)</p>
          </div>

          <div class="user-card-allergy-list" style="margin-top: 1%">

              @if (@Model.JoinEntities.Count == 0)
              {
                <p>This user does not have any allergies :-|</p>
              }
              else
              {
                <h5>This user has these allergies:</h5>
                    <ul>

                        @foreach(var join in Model.JoinEntities)
                        {
                          <li class="list-button" style="transform: scale(0.8); width: max-content;">

                           @Html.ActionLink($"{join.userAllergy.Allergy}", "Details", "UserAllergies", new { id = join.userAllergy.UserAllergyId } )

                              @using (Html.BeginForm("DeleteAllergy", "UserProfiles"))
                                {
                                  @Html.Hidden("joinId", @join.ProfileAllergyId)
                                  <input type="submit" value="  X " class='bi bi-trash' id="trashyboi"
                                      style='
                                        color: crimson;
                                        font-weight: 800;
                                        background-color: transparent;
                                        border-style: none;
                                        margin: 0;
                                      '/>
                                }

                          </li>
                        }
                    </ul>
                }
          </div>

        </div>
        <img class="card-img-top"src="~/img/@Model.ImageUrl" />
    </div>

    <div class="user-card-content-bio">
      <h4>@Html.DisplayNameFor(model => model.Bio):</h4> <p>@Html.DisplayFor(model => model.Bio)</p>
    </div>

    <div class="user-button-footer" id="user-config">
        <button>@Html.ActionLink("Edit Profile", "Edit", new { id = Model.UserProfileId })</button>
        <button>@Html.ActionLink("Delete Profile", "Delete", new { id = Model.UserProfileId })</button>
        <button>@Html.ActionLink("Add an Allergy", "AddAllergy", new { id = Model.UserProfileId })</button>
    </div>

  </div>

</div>

AtchooClient/Views/UserProfiles/Edit.cshtml
@model AtchooClient.Models.UserProfile

<h4>Edit Profile:</h4>

@using (Html.BeginForm("Edit","UserProfiles",FormMethod.Post,new {enctype ="multipart/form-data"}))
{
  @Html.HiddenFor(model => model.UserProfileId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name, new { value="model.Name", required = "required" })<br>

  <br>@Html.Label("Date of Birth")
  @Html.TextBoxFor(model => model.DOB, new { required = "required", @type = "date", value = "model.DOB" })<br>

  <br>@Html.Label("Bio")
  @Html.EditorFor(model => model.Bio, new {htmlAttributes = new {maxlength=250, @class = "form-control"}})

  <input  type="file" name="FrontImage" required/>

  <input type="submit" value="save" class="btn btn-success" />
}
<br><p>@Html.ActionLink("Back To Profile", "Index")</p>

AtchooClient/Views/UserProfiles/Index.cshtml
  <div class="user-page" style="
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  ">
    
    @if (Model.Count != 0)
    {
    
        @foreach (UserProfile userProfile in Model)
        {
          <div class="card h-100" style="max-width: 20rem;">
            <div class="card-title">
              <li class="list-button">@Html.ActionLink("View Your Profile", "Details", new { id = userProfile.UserProfileId })</li>
            </div>
            <img class="card-img-top"src="~/img/@userProfile.ImageUrl" /> 
          </div>
        }
      
    } 
    else
    {
      <h3></h3>
      <button style="margin-top: 10%">@Html.ActionLink("Create Your Account", "Create", "UserProfiles")</button>
    }
    
  </div>

AtchooClient/Views/UserProfiles/ThankYou.cshtml
@model AtchooClient.Models.UserProfile

@{
   ViewBag.Title = "ThankYou";
}

@if(TempData["alertMessage"] != null)
   {
      @Html.Raw(TempData["alertMessage"])
   }

<h1>You've Already added this Allergy</h1>

<button>@Html.ActionLink("Go Back", "Index", "UserProfiles")</button>